name: docker image build
on: workflow_dispatch
jobs:
  linting: 
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4.2.2
      - name: Linting Action
        uses: codebeltnet/codeql-scan@v1.0.0
        with: 
          languages: python

  docker:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4.2.2
      - name: docker image build
        run: |
          docker build -t myapp .
          docker images ls 
        
      
